### PR TITLE
add plotter

### PR DESCRIPTION
**Pull request by dnabanita7**
I have used Makie.jl to plot. I have added a basic layout or structure of the plotter.jl. I will be adding features and other arguments along the way. [Link to issue](https://github.com/IBM/AutoMLPipeline.jl/issues/62)

### CODE REVIEW

**Comment by ppalmes** [comment]
I think you don't need to ask for the dim because you can derive it from the `axes` or columns. I suggest you use the `axes` vector to indicate which column of dataframe is for x,y, and z. So for example, Plotter([10,3,1]) means that column 10 is x-axis, column 3 is y-axis and column 1 is z-axis. The length of the `axes` vector determines the dimension. You can create some checking such that if the `axes` is empty or more than 3 elements, you return an error. Also, you check if the column types indicated are numerical values, otherwise, return an error too. In the future, you can also support a barplot for categorical variables or you can make it as a plottyype enum type to cater for different types of plotting (line, density, pie, etc).

**Comment by dnabanita7** [comment]
I didn't understand the note

**Comment by ppalmes** [comment]
you have to test to validate that the plot exists. normally, you will know by looking at the plot but in automated testing where there is no person to check if the plot exists, you have to either check if the plot object exists or how much is the size of the plot generated to make sure the function to plot works.

**Comment by dnabanita7** [comment]
I was searching for testing the plot object. I didn't find any. The approaches I took :
```
1) Check the eltype of ``fit_transform!()`` object. But since all ``fit_transform!()`` is ``Any`` it is not possible to use it.
2) Check for the attributes of the res object where ``res = fit_transform!(pipe,X)`` which are : 
Dict{Any,Any} with 26 entries:
  :colormap => :viridis
  :visible => true
  :axis => Dict{Any,Any} with 0 entries
  :axis2d => Dict{Any,Any} with 0 entries
  :markersize => 0.1
  :camera => Automatic()
  :linestyle => nothing
  :font => "Dejavu Sans"
  :axis_type => Automatic()
  :raw => false
  :clear => true
  :legend => Dict{Any,Any} with 0 entries
  :axis3d => Dict{Any,Any} with 0 entries
  :resolution => (960, 540)
  :update_limits => true
  :center => true
  :marker => HyperSphere{2,T} where T
  :color => :black
  :show_legend => false
  :padding => Float32[0.05, 0.05, 0.05]
  :SSAO => Dict{Any,Any} with 3 entries:
  :blur => 2
  :bias => 0.025
  :radius => 0.5
  :palette => Dict{Any,Any} with 4 entries:
  :color => ColorTypes.RGB{Float64}[RGB{Float64}(0.901961,0.623529,0.0), RGB{Float64}(0.337255,0.705882,0.913725), RGB{Float64}(0.0,0.619608,0.45098), RGB{Float64}(0.941176,0.894118,0.258824), RGB{Float64}(0.0,0.447059,0.698039), RGB{Float64}(0.835294,0.368627,0.0), RGB{Float64}(0.8,0.47451,0.654902)]
  :side => [:left, :right]
  :linestyle => Union{Nothing, Symbol}[nothing, :dash, :dot, :dashdot, :dashdotdot]
  :marker => [:circle, :xcross, :utriangle, :diamond, :dtriangle, :star8, :pentagon, :rect]
  :backgroundcolor => :white
  :show_axis => true
  :scale_plot => true
  :limits => Automatic()
and i can't think of a way to use any for testing as I was trying to implement something like this : 
```
def test_plot_square1():
    x, y = [0, 1, 2], [0, 1, 2]
    line, = plot_square(x, y)
    x_plot, y_plot = line.get_xydata().T
    np.testing.assert_array_equal(y_plot, np.square(y))
```
```

**Comment by ppalmes** [comment]
this is ok. can you check why the test is failing?

**Pull request closed without merging**
